# Generated by Django 4.2.3 on 2023-07-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base', '0002_topic_island_host_message_island_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='topic',
            old_name='topic',
            new_name='name',
        ),
    ]
